// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=storage_mock.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockInterface) Del(ctx context.Context, params DelParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockInterfaceMockRecorder) Del(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockInterface)(nil).Del), ctx, params)
}

// Put mocks base method.
func (m *MockInterface) Put(ctx context.Context, params PutParams) (PutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, params)
	ret0, _ := ret[0].(PutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockInterfaceMockRecorder) Put(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockInterface)(nil).Put), ctx, params)
}

// Url mocks base method.
func (m *MockInterface) Url(ctx context.Context, params UrlParams) (UrlResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Url", ctx, params)
	ret0, _ := ret[0].(UrlResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Url indicates an expected call of Url.
func (mr *MockInterfaceMockRecorder) Url(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Url", reflect.TypeOf((*MockInterface)(nil).Url), ctx, params)
}
